version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: python main.py
    depends_on:
      - redis
  redis:
    image: "redis:alpine3.19"
    ports:
      - "6379:6379"